### ISSUE TITLE
w-progress 进度条样式错误

### ISSUE THREAD

**Issue by GodMeowIceSun** [janghood/wash-painting-ui#22]
描述: 新项目vue3.2.13 无法显示进度条
BTW: 很多样式都有问题

**Comment by higuaifan** [comment]
Hi. 感谢您的使用，这玩意居然有人用真是受宠若惊。

请问导入了样式文件嘛？
``` css
@import '/node_modules/@higuaifan/wash-painting-ui/dist/style.css';
```

样式文件不导入可能会产生样式丢失的。

如果导入了的话，麻烦提供一下开发环境和其他有问题的组件样式截图（一张即可）。

**Comment by GodMeowIceSun** [comment]
哈哈，应该是没有导入样式文件, 偶然间看到了一幅水墨画，然后突然想做这个风格的，就发现了这个项目，如果有机会有时间的话，我也会参与进开源项目的功能开发

**Comment by higuaifan** [comment]
> 哈哈，应该是没有导入样式文件, 偶然间看到了一幅水墨画，然后突然想做这个风格的，就发现了这个项目，如果有机会有时间的话，我也会参与进开源项目的功能开发

哈哈好的，另外如果使用中遇到什么问题的话可以联系我。

**Comment by GodMeowIceSun** [comment]
对了，@higuaifan , npm 仓库建议非测试版本挂@latest标签, 测试版本挂@next或者@beta标签更好一些 :)

**Comment by GodMeowIceSun** [comment]
`npm publish --tag beta`
`npm publish --tag next`

**Comment by higuaifan** [comment]
> `npm publish --tag beta` `npm publish --tag next`

主要一开始玩票性质偏大，一直感觉会有些破坏性的改动。。所以也没挂标签哈哈，感谢提醒，后面我注意一下。

**Comment by GodMeowIceSun** [comment]
> 

加油哈，挂一个相对稳定的版本为latest，然后后面其他的主版本发布先用next然后测试版本发布用beta就好啦，这样相对语义会更明确点，相对来说在依赖树里能更清楚一些

**Comment by higuaifan** [comment]
> > 
> 
> 加油哈，挂一个相对稳定的版本为latest，然后后面其他的主版本发布先用next然后测试版本发布用beta就好啦，这样相对语义会更明确点，相对来说在依赖树里能更清楚一些

哈哈好的，后续我们会注意这个问题，感谢支持啦😁
